# Generated by Django 3.2.8 on 2021-10-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_comentcrm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentcrm',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='statuscrm',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
